permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge

# markdown: redcarpet2
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

kramdown:
  input: GFM

# 作者信息
author: 
  name: 李聪
  email: spritemoss@gmail.com
  link: http://
  weibo: http://weibo.com/aiziyuer
  github: http://github.com/aiziyuer

# 站点信息
title: Moss's Blog
description: Moss's Blog
url: http://aiziyuer.github.io/Blog/
#rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar:  assets/img/butterflies_800x800.jpg
favicon: assets/img/butterflies_favor.ico
