permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-feed

kramdown:
  syntax_highlighter: rouge
  input: GFM

exclude:
  - CNAME
  - README
  - "*.BAK"
  - bower_components
  - node_modules
  - gulpfile.js
  - "*.sublime-project"
  - "*.sublime-workspace"
  - bower.json
  - "*.log"
  - package.json
  
# 作者信息
author: 
  name: moss.licong
  email: ziyu0123456789@gmail.com
  link: http://
  weibo: http://weibo.com/aiziyuer
  github: http://github.com/aiziyuer

# 站点信息
title: Moss's Blog
description: Moss's Blog
url: http://aiziyuer.github.io/Blog/
rss_url: feed.xml

disqus:
  shortname: aiziyuer

# avatar头像及Favicon
avatar:  /assets/img/butterflies_800x800.jpg
favicon: /assets/img/butterflies_favor.ico
